#!/usr/bin/env bash
# nix/gen-patches.sh — convert build.sh's 72 imperative apply_* into committed
# unified diffs (overlay/patches/*.patch + series), the quilt way.
#
# Method (faithful + self-auditing): extract the pristine assembled tree
# (gameLove, pre-patch), then replay build.sh's EXACT patch call order against
# it, using git to capture each call's diff. A call that changes nothing is a
# SILENT-DROP audit hit — a fix the legacy build is shipping without (its anchor
# drifted but build.sh only log_warn-skips it).
#
# Output: overlay/patches/NN-<name>.patch, overlay/patches/series,
#         overlay/patches/GEN-REPORT.txt
set -uo pipefail
ROOT_WT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="/home/jluker/balatro-cryptid-mobile"          # main checkout: build.sh + patches/
OUT="$ROOT_WT/overlay/patches"
WORK="$(mktemp -d)"; B="$WORK/game"
# always clean up the workdir — $B becomes a git repo (50+ commits of the full game tree),
# so without this each run leaks a multi-hundred-GB /tmp/tmp.* dir. chmod first: git's object
# store is read-only, which makes a plain rm -rf fail partway and leave the dir behind.
trap 'chmod -R u+w "$WORK" 2>/dev/null; rm -rf "$WORK"' EXIT
SERIES="$OUT/series"; REPORT="$OUT/GEN-REPORT.txt"
# byte-exact git: ignore global/system config so CRLF (Cryptid shaders) is never
# normalised — the generated diffs must match the real files at apply time.
GIT() { GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null \
        git -C "$B" -c core.autocrlf=false -c core.safecrlf=false \
            -c user.email=x@x -c user.name=x "$@"; }

# gen-patches owns ONLY the mechanical top-level patches; overlay/patches/manual/
# holds hand-maintained re-anchored ports (silent-skip fixes) that are NOT
# mechanically derivable — never clobber those.
rm -f "$OUT"/*.patch

echo "[gen] materialising pristine gameLoveBase (pre-patch tree)..."
GLB="$(nix-build "$ROOT_WT/nix/balatro-cryptid.nix" -A gameLoveBase --no-out-link)"
mkdir -p "$B"; cp -r "$GLB"/. "$B"; chmod -R u+w "$B"

echo "[gen] sourcing build.sh apply_* (without main)..."
sed '/^main "\$@"$/d' "$ROOT_WT/scripts/build.sh" > "$WORK/build-lib.sh"
# shellcheck disable=SC1090
source "$WORK/build-lib.sh"
set +e
# scripts + patches are tracked → read them from the worktree (the branch's own,
# committed versions). mods/src are gitignored → only in the main checkout.
SCRIPT_DIR="$ROOT_WT/scripts"; PROJECT_DIR="$ROOT_WT"; PATCHES_DIR="$ROOT_WT/patches"
SRC_DIR="$SRC/src"; MODS_DIR="$SRC/mods"; game_dir="$B"
export SOURCE_DATE_EPOCH=1700000000 TZ=UTC

GIT init -q; GIT add -A; GIT commit -qm pristine >/dev/null

: > "$REPORT"
{ echo "# generated by nix/gen-patches.sh — apply order matches scripts/build.sh"; } > "$SERIES"
seq=0
# Caps that legitimately produce no diff. Reason 'manual/NN' = the fix is
# re-anchored in overlay/patches/manual/ (different file/context, the cap call
# stays only as a pointer); 'upstream' = the source already contains the fix.
# Any cap NOT listed here that produces an empty diff is unexpected anchor drift
# (the fix silently shipped nothing) and ABORTS the run.
declare -A EXPECTED_SKIP=(
  [sticky_fingers_guard]="manual/60 — nil-guards now live in Mods/sticky-fingers/main.lua"
  [drag_reject_feedback]="manual/61 — feedback now in Mods/sticky-fingers/main.lua"
  [mod_toggle_removed]="manual/63 — re-anchored to revised Steamodded ui.lua"
  [drag_self_drop_exclude]="manual/59 — re-anchored to revised controller.lua"
  [cryptid_oil_lamp_fix]="upstream — Cryptid 0.5.16a already declares 'local other_joker'"
)
cap() {
  local name="$1"; shift
  local rc=0 errout
  errout="$( ( "$@" ) 2>&1 >/dev/null )" || rc=$?   # subshell isolates apply_* exits
  # main_lua is patch_main_lua.py and MUST succeed; bash apply_* may benign-exit.
  if [ "$rc" -ne 0 ] && [ "$name" = "main_lua" ]; then
    echo "[gen] FATAL: $name failed (rc=$rc):" >&2; printf '%s\n' "$errout" >&2; exit 1
  fi
  GIT add -A
  if GIT diff --cached --quiet HEAD; then
    if [[ -v EXPECTED_SKIP[$name] ]]; then
      printf 'SKIP-EXPECTED  %-26s  # %s\n' "$name" "${EXPECTED_SKIP[$name]}" | tee -a "$REPORT"
    else
      echo "[gen] FATAL: $name produced no diff — unexpected anchor drift (fix silently dropped)." >&2
      echo "[gen]   If covered by a manual/ patch or upstream, add it to EXPECTED_SKIP." >&2
      exit 1
    fi
  else
    seq=$((seq+1)); local pf; pf="$(printf '%02d-%s.patch' "$seq" "$name")"
    GIT diff --cached HEAD > "$OUT/$pf"
    GIT commit -qm "$name" >/dev/null
    echo "$pf" >> "$SERIES"
    printf 'OK    %-28s -> %s\n' "$name" "$pf" | tee -a "$REPORT"
  fi
}

# ── faithful replay of build.sh patch order ───────────────────────────────
# NOTE: build_stamp is NOT captured — it is injected deterministically in
# gameLoveBase (the legacy stamp was date+githash, non-reproducible). The
# globals.lua here already carries CRYPTID_MOBILE_BUILD.
cap sticky_fingers_guard      apply_sticky_fingers_guard "$B/functions/misc_functions.lua"
cap crt_fix                   apply_crt_fix "$B/resources/shaders/CRT.fs"
cap android_settings_fix      apply_android_settings_fix "$B/globals.lua"
cap mobile_graphics_defaults  apply_mobile_graphics_defaults "$B/globals.lua"
cap android_video_settings    apply_android_video_settings_fix "$B/functions/UI_definitions.lua"
cap android_quit_fix          apply_android_quit_fix "$B/functions/button_callbacks.lua"
cap drag_reject_feedback      apply_drag_reject_feedback "$B/functions/button_callbacks.lua"
cap settings_debug_tab        apply_settings_debug_tab "$B/functions/UI_definitions.lua"
cap debug_overlay             apply_debug_overlay "$B/game.lua" "$B/functions/misc_functions.lua"
cap main_lua                  python3 "$SCRIPT_DIR/patch_main_lua.py" "$B/main.lua"
# patch_mods_dir (mods_dir=$B/Mods, root=$B)
cap mods_build_stamp_menu     apply_build_stamp_menu "$B/Mods/Steamodded/src/ui.lua"
cap shader_eof_newlines       apply_shader_eof_newlines "$B"
cap blur_shader_reorder       apply_blur_shader_reorder "$B/Mods/Cryptid/assets/shaders/blur.fs"
cap glitch_shader_fix         apply_glitch_shader_fix "$B/Mods/Cryptid/assets/shaders/glitched.fs"
cap glitch_shader_range_fix   apply_glitch_shader_range_fix "$B/Mods/Cryptid/assets/shaders/glitched.fs"
cap glitched_b_fix            apply_glitched_b_fix "$B/Mods/Cryptid/assets/shaders/glitched_b.fs"
cap cryptid_dead_copy_fix     apply_cryptid_dead_copy_fix "$B/Mods/Cryptid/lib/calculate.lua"
cap cryptid_flip_side_cache   apply_cryptid_flip_side_cache "$B/Mods/Cryptid/lib/calculate.lua" "$B/Mods/Cryptid/lib/overrides.lua"
cap cryptid_events_guard      apply_cryptid_events_guard "$B/Mods/Cryptid/lib/calculate.lua"
cap amulet_config_hardening   apply_amulet_config_hardening "$B/talisman/configinit.lua"
cap amulet_calc_delay         apply_amulet_calc_delay "$B/talisman/coroutine.lua"
cap amulet_overlay_fit        apply_amulet_overlay_fit "$B/talisman/coroutine.lua"
# structural_mods_lock: manual/62 covers all 3 lovelyignore sites (incl. lovely-compat);
# apply_structural_mods_lock only guards the 2 SMODS.MODS_DIR sites. Keep as manual
# to preserve the third-site guard — gen-patches must not also cap this.
# cap structural_mods_lock      apply_structural_mods_lock "$B/Mods/Steamodded/src/preflight/loader.lua"
cap smods_disabled_pool_gate  apply_smods_disabled_pool_gate "$B/Mods/Steamodded/src/utils.lua"
cap mod_toggle_removed        apply_mod_toggle_removed "$B/Mods/Steamodded/src/ui.lua"
cap cryptid_to_big_elim       apply_cryptid_to_big_elim "$B/Mods/Cryptid/items/epic.lua" "$B/Mods/Cryptid/items/exotic.lua" "$B/Mods/Cryptid/items/m.lua"
cap cryptid_demicolon         apply_cryptid_demicolon_no_chain "$B/Mods/Cryptid/items/epic.lua"
cap cryptid_oil_lamp_fix      apply_cryptid_oil_lamp_local_fix "$B/Mods/Cryptid/items/misc_joker.lua"
cap cry_vanilla_gameset       apply_cry_vanilla_gameset "$B/Mods/Cryptid/lib/gameset.lua" "$B/Mods/Cryptid/Cryptid.lua" "$B/Mods/Cryptid/localization/en-us.lua"
cap cry_blind_choice_guard    apply_cry_blind_choice_guard "$B/Mods/Cryptid/lib/overrides.lua" "$B/Mods/Cryptid/lib/gameset.lua"
cap cry_forcetrigger_guard    apply_cry_forcetrigger_depth_guard "$B/Mods/Cryptid/lib/forcetrigger.lua"
cap hand_level_no_recalc      apply_hand_level_no_recalc "$B/Mods/Steamodded/src/ui.lua"
# rest of build_apk
cap shake_trig_guard          apply_shake_trig_guard "$B/functions/common_events.lua"
cap forced_key_guard          apply_forced_key_guard "$B/functions/common_events.lua"
cap disabled_center_skip      apply_disabled_center_skip "$B/cardarea.lua"
cap tap_description_persist   apply_tap_description_persist "$B/engine/controller.lua"
cap cursor_down_uptime_fix    apply_cursor_down_uptime_fix "$B/engine/controller.lua"
cap drag_self_drop_exclude    apply_drag_self_drop_exclude "$B/engine/controller.lua"
cap ui_colour_guard           apply_ui_colour_guard "$B/engine/ui.lua"
cap ui_o_detached_guard       apply_ui_o_detached_guard "$B/engine/ui.lua"
cap drag_select               apply_drag_select "$B/engine/controller.lua" "$B/globals.lua" "$B/functions/UI_definitions.lua"
cap telemetry_toggles         apply_telemetry_toggles "$B/functions/UI_definitions.lua" "$B/game.lua"
cap overlay_menu_fit          apply_overlay_menu_fit "$B/functions/UI_definitions.lua"
cap shadow_height_fix         apply_shadow_height_fix "$B/card.lua"
cap card_to_big_elim          apply_card_to_big_elim "$B/card.lua"
cap scoring_loop_cache        apply_scoring_loop_cache "$B/functions/state_events.lua"
cap ctx_table_hoist           apply_ctx_table_hoist "$B/functions/state_events.lua"
cap lvl_prefix_cache          apply_lvl_prefix_cache "$B/functions/common_events.lua"
cap parse_highlighted_lean    apply_parse_highlighted_lean "$B/cardarea.lua"
cap card_eval_config_elide    apply_card_eval_config_elide "$B/functions/common_events.lua"
cap empty_pool_guard          apply_empty_pool_guard "$B/functions/common_events.lua"
cap get_x_same_lean           apply_get_x_same_lean "$B/functions/misc_functions.lua"
cap dynatext_glyph_cache      apply_dynatext_glyph_cache "$B/engine/text.lua"
cap letter_table_reuse        apply_letter_table_reuse "$B/engine/text.lua"
cap nugc_adaptive             apply_nugc_adaptive "$B/functions/misc_functions.lua"
cap moveable_sleep            apply_moveable_sleep "$B/engine/moveable.lua"
cap moveable_shadow_lists     apply_moveable_shadow_lists "$B/globals.lua" "$B/engine/moveable.lua" "$B/game.lua"
cap event_burst_attrib        apply_event_burst_attrib "$B/engine/event.lua"
cap event_queue_compact       apply_event_queue_compact "$B/engine/event.lua"
cap ui_func_throttle          apply_ui_func_throttle "$B/engine/ui.lua"
cap blind_select_defer        apply_blind_select_defer "$B/game.lua"
cap blind_select_tall         apply_blind_select_tall "$B/functions/UI_definitions.lua"
cap draw_shader_nil_reset     apply_draw_shader_nil_reset "$B/engine/sprite.lua" "$B/SMODS/_/src/card_draw.lua" "$B/card.lua" "$B/blind.lua" "$B/functions/misc_functions.lua"

# append hand-maintained patches (re-anchored silent-skip ports) after the
# mechanical series, in name order — these apply last.
if compgen -G "$OUT/manual/*.patch" >/dev/null 2>&1; then
  echo "[gen] appending hand-maintained manual/ patches:"
  for mp in "$OUT"/manual/*.patch; do
    echo "manual/$(basename "$mp")" >> "$SERIES"
    echo "  + manual/$(basename "$mp")"
  done
fi

echo
echo "===== SUMMARY ====="
ok=$(grep -c '^OK' "$REPORT"); sk=$(grep -c '^SKIP-EXPECTED' "$REPORT")
echo "patches generated: $ok    expected-skips: $sk"
echo "--- EXPECTED SKIPS (covered by a manual/ patch or upstream-absorbed) ---"
grep '^SKIP-EXPECTED' "$REPORT" || echo "(none)"
echo "patches + series + GEN-REPORT.txt in $OUT"
